// Liste des 58 Wilayas d'Algérie
export const ALGERIA_WILAYAS = [
    'Adrar',
    'Aïn Defla',
    'Aïn Témouchent',
    'Alger',
    'Annaba',
    'Batna',
    'Béchar',
    'Béjaïa',
    'Biskra',
    'Blida',
    'Bordj Bou Arréridj',
    'Bouira',
    'Boumerdès',
    'Chlef',
    'Constantine',
    'Djelfa',
    'El Bayadh',
    'El Oued',
    'El Tarf',
    'Ghardaïa',
    'Guelma',
    'Illizi',
    'Jijel',
    'Khenchela',
    'Laghouat',
    'M\'Sila',
    'Mascara',
    'Médéa',
    'Mila',
    'Mostaganem',
    'Naâma',
    'Oran',
    'Ouargla',
    'Oum El Bouaghi',
    'Relizane',
    'Saïda',
    'Sétif',
    'Sidi Bel Abbès',
    'Skikda',
    'Souk Ahras',
    'Tamanghasset',
    'Tébessa',
    'Tiaret',
    'Tindouf',
    'Tipaza',
    'Tissemsilt',
    'Tizi Ouzou',
    'Tlemcen',
    'Touggourt',
    'In Guezzam',
    'In Salah',
    'Timimoun',
    'Bordj Badji Mokhtar',
    'Ouled Djellal',
    'Béni Abbès',
    'Aïn Salah',
    'Djanet',
    'El M\'Ghair',
] as const;

export type Wilaya = typeof ALGERIA_WILAYAS[number];
